### ISSUE TITLE
Close a TestRun after is the tests finished. 

### ISSUE THREAD

**Issue by estefafdez** [qase-tms/qase-javascript#17]
### More information:

- Every time that a spec runs a new TestRun is created. 
- After a spec is finished, the TestRun remains open. 
- If you run the test every single night, you will have unlimited TestRun opened (one per spec) without being closed. 

It would be great that the TestRun is closed after is finished. 

Thanks!

**Comment by zeburek** [comment]
@estefafdez you can check settings of your project for this feature (last one on the screen):
![image](https://user-images.githubusercontent.com/20853475/120756501-fcbb8700-c517-11eb-821b-8f4f8ced613c.png)

**Comment by yetithefoot** [comment]
Hello. I'm using `jest-qase-reporter` and event with the checkbox set it doesn't complete the Test run. Is it possible to complete the test runs created by `jest-qase-reporter`?

**Comment by zeburek** [comment]
@yetithefoot I've pushed the fix for jest reporter, please check in version 1.1.0

**Comment by yetithefoot** [comment]
@zeburek thanks.

However, the problem still exists in `1.1.0`.   

At the moment when `onRunComplete` is invoked, the [`runId` variable is still `undefined`](https://github.com/qase-tms/qase-javascript/commit/a6a00db60c956d423bb8593276c9570fdb077b94#diff-055b40a3e986636069be46045512d14b0cd8ed4bcb802c3a70bc8730e4b7fe30R107), because the callback from the `createRun` [function is also asynchronous](https://github.com/qase-tms/qase-javascript/commit/a6a00db60c956d423bb8593276c9570fdb077b94#diff-055b40a3e986636069be46045512d14b0cd8ed4bcb802c3a70bc8730e4b7fe30R78) and happens after the `onRunComplete`.

As I see in Jest sources, the TestDispatcher [awaits the testResults](https://github.com/facebook/jest/blob/master/packages/jest-core/src/TestScheduler.ts#L279), and only after [invokes the `onRunComplete`](https://github.com/facebook/jest/blob/master/packages/jest-core/src/TestScheduler.ts#L298). So I guess the best option is to follow the reporter interface and return a promise for each  [`publishCaseResult`](https://github.com/qase-tms/qase-javascript/commit/a6a00db60c956d423bb8593276c9570fdb077b94#diff-055b40a3e986636069be46045512d14b0cd8ed4bcb802c3a70bc8730e4b7fe30R217) and await all of them before returning from, something like:

```javascript
   QaseReporter.prototype.onTestResult = function (test, testResult, aggregatedResult) {
        return Promise.allSettled(testResult.testResults.map(this.publishCaseResult));
    };
```

**Comment by zeburek** [comment]
@yetithefoot I think this:
> createRun function is also asynchronous and happens after the onRunComplete

It may only happen when you run a small number of tests, or they are faster than 500ms (create run execution time).

Have you tried to use this in real projects with real testcases?

---

BTW, I will take a look at your example, I don't think it will require a large refactoring, so I will keep the issue open.

**Comment by yetithefoot** [comment]
Yep. It works on a larger test cases set. Thanks.

**Comment by evgenykochetkov** [comment]
Hi everyone! The problem is fixed in `jest-qase-reporter` v1.2.0.
