### ISSUE TITLE
Error executing command 'npm list --depth=10 --json': Error: Command failed: npm list --depth=10 --json

### ISSUE THREAD

**Issue by marc-thomas** [qase-tms/qase-javascript#774]
We have a mono repo setup and we have `packages/e2e` and we are importing `packages/core` into our e2e package so we can access constants. Everything is installed correctly, but when I run the tests it throws some errors - but then the tests run fine and everything pushes to qase.

Looks like it is trying to list out all the packages for the core packages as well, but failing.

I guess this is more of an annoying thing I just don't want to look at every time I run the tests - can I disable the npm list command?

This error only occurs if I am using `playwright-qase-reporter`

### Additional Information

**Versions:**
- Node.js: 18.19.1
- playwright-qase-reporter: ^2.0.17
- @playwright/test: ^1.50.1

**Package Structure:**
```json
// packages/e2e/package.json
{
  "name": "@app/e2e",
  "version": "1.0.0",
  "devDependencies": {
    "@app/core": "^4.8.21",
    "@playwright/test": "^1.50.1",
    "@types/node": "^18.17.0",
    "eslint-plugin-playwright": "^0.15.3"
  },
  "dependencies": {
    "dotenv": "^16.4.7",
    "playwright-qase-reporter": "^2.0.17"
  }
}
```

**Reporter Configuration:**
```typescript
 reporter: [
    ["html"], // Keep existing HTML reporter
    [
      "playwright-qase-reporter",
      {
        mode: "testops",
        debug: false,
        environment: env,
        testops: {
          api: {
            token: process.env.QASE_API_TOKEN,
          },
          project: "SPT",
          uploadAttachments: true,
          run: {
            complete: false,
            id: process.env.QASE_RUN_ID
              ? parseInt(process.env.QASE_RUN_ID)
              : undefined,
          },
        },
      },
    ],
```

**Full Error Output:**

```
npm run e2e:test:beta
Error executing command 'npm list --depth=10 --json': Error: Command failed: npm list --depth=10 --json
npm ERR! code ELSPROBLEMS
npm ERR! missing: @playwright/test@^1.50.1, required by @app/e2e@1.0.0
npm ERR! missing: @types/node@^18.17.0, required by @app/e2e@1.0.0
npm ERR! missing: dotenv@^16.4.7, required by @app/e2e@1.0.0
npm ERR! missing: eslint-plugin-playwright@^0.15.3, required by @app/e2e@1.0.0
npm ERR! missing: playwright-qase-reporter@^2.0.17, required by @app/e2e@1.0.0
[... additional core package dependency errors ...]

npm ERR! A complete log of this run can be found in: /.npm/_logs/debug-0.log

    at checkExecSyncError (node:child_process:890:11)
    at Object.execSync (node:child_process:962:15)
    at execCommand (/node_modules/qase-javascript-commons/dist/utils/hostData.js:74:19)
    at getPackageVersion (/node_modules/qase-javascript-commons/dist/utils/hostData.js:122:24)
    at getHostInfo (/node_modules/qase-javascript-commons/dist/utils/hostData.js:163:24)
    at new QaseReporter (/node_modules/qase-javascript-commons/dist/qase.js:87:53)
    at Function.getInstance (/node_modules/qase-javascript-commons/dist/qase.js:267:37)
    at new PlaywrightQaseReporter (/node_modules/playwright-qase-reporter/dist/reporter.js:251:64)
    at createReporters (/node_modules/playwright/lib/runner/reporters.js:66:55)
    at Runner.runAllTests (/node_modules/playwright/lib/runner/runner.js:64:23)
    at runTests (/node_modules/playwright/lib/program.js:215:18)
    at t.<anonymous> (/node_modules/playwright/lib/program.js:55:7) {
  status: 1,
  signal: null,
output: [
    null,
    <Buffer [package info]>,
    <Buffer [npm error info]>
],
pid: [process_id],
stdout: <Buffer [package info]>,
stderr: <Buffer [npm error info]>
[INFO] qase: Test should login successfully with valid credentials TA-1 passed
[INFO] qase: Test should fail login with invalid credentials TA-2 passed
[INFO] qase: Test should login successfully with valid credentials TA-1 passed
[INFO] qase: Test should fail login with invalid credentials TA-2 passed
[INFO] qase: Test should login successfully with valid credentials TA-1 passed
[INFO] qase: Test should fail login with invalid credentials TA-2 passed
```

thanks

**Comment by gibiw** [comment]
@marc-thomas Hi! Thanks for reporting the issue. We’ve fixed it in version 2.2.18.

**Comment by marc-thomas** [comment]
hi @gibiw 

I didn't actually have `qase-javascript-commons` installed at all before - I have installed it now, but the error persists

```
json
  "dependencies": {
    "dotenv": "^16.4.7",
    "playwright-qase-reporter": "^2.0.17",
    "qase-javascript-commons": "2.2.18"
  }
```

**Comment by gibiw** [comment]
We haven’t received a response in 2 weeks. If the issue is still relevant, please reopen this one or create a new one.
